### ISSUE TITLE
Directory Structure

### ISSUE THREAD

**Issue by fraserh** [fraserh/waldi#10]
Decide how we will store different store/category pages:
- Directories
- File names

**Comment by matthewpalmer** [comment]
I'm happy to go with whatever's convenient for you.

As you said on fb, maybe like

```
coles/
  - fruit-1.html
  - fruit-2.html
  - fruit-3.html
  - ...
  - meat-1.html
  - ...
woolworths/
  - fruit-1.html
  - ...
```

How do you want to handle metacharacters in category names? (think i've seen &, -, ' ' so far)
