### ISSUE TITLE
Incremental crawling

### ISSUE THREAD

**Issue by matthewpalmer** [fraserh/waldi#6]
Add incremental crawling so if a crawling process drops out we can specify a point or URL to start up again from

**Comment by matthewpalmer** [comment]
Will find a queueing system so we can jump back in when the crawler inevitably crashes

**Comment by fraserhemp** [comment]
Maybe we should prevent crashes by only scraping short bursts of pages, restarting phantom for each burst? That assumes we are certain it won't crash for n scrapes though.

**Comment by fraserhemp** [comment]
(as well as handling crashes with the queue)

**Comment by matthewpalmer** [comment]
Yeah that’s probably a good idea.
A quick way to do it would be to have a timeout of like 30 seconds for each scrape, and if we exceed that then just crash and restart the process. Will mean that we don’t have to hard-code n scrapes. 

Not sure which is easier to implement, I’m happy with whichever

**Comment by fraserhemp** [comment]
I guess the 30 second method would be easier? Easy enough to change if it doesn't work out

**Comment by fraserhemp** [comment]
btw, what are you running this on? Macbook air?

**Comment by matthewpalmer** [comment]
Yeah base model 2011 macbook air

**Comment by matthewpalmer** [comment]
Do you have any preference for the queue? Probably going to go with beanstalkd otherwise

**Comment by fraserhemp** [comment]
Once I get internet, I might give my bigger laptop a go.

**Comment by fraserhemp** [comment]
No preference, use whatever.
