### ISSUE TITLE
Fix crawler memory leak

### ISSUE THREAD

**Issue by matthewpalmer** [fraserh/waldi#8]
Memory usage blows out pretty quick.

**Comment by fraserh** [comment]
what does the profiling log?

**Comment by matthewpalmer** [comment]
Haven’t had a deep look yet. Just noticed memory usage went from like 80mb to 200mb in activity monitor for that process so I though it was worth investigating.=

**Comment by fraserh** [comment]
That's not too bad, but yeah, probably a good idea to keep an eye on it.

**Comment by matthewpalmer** [comment]
Fixed in ae414b9
